### ISSUE TITLE
cannot use 'drush upwd' to create a password containing spaces

### ISSUE THREAD

**Issue by byrond** [palantirnet/the-vagrant#36]
Not sure if this is anecdotal or not, but running the-vagrant on Ubuntu 16.04.1, I can't set a password containing spaces using drush.  It works fine through the UI.  For example:

drush user-password admin --password="correct horse battery staple"

Note: the command above claims it succeeds, but attempting to login with the password fails.  Setting a password that contains no spaces using the command above works correctly.

**Comment by becw** [comment]
Does this work with drush on other environments?

**Comment by byrond** [comment]
@becw I seem to remember it does work on other environments, but I will double-check and report back.  I will also make sure I can reproduce the issue on the-vagrant since it has been a while since I reported it.

**Comment by becw** [comment]
I think this affects `drush sqlq` and `drush php-eval` as well. @damontgomery found that it was related to the drush wrapper script installed by `the-vagrant`: https://github.com/palantirnet/the-vagrant/blob/develop/bin/the-vagrant-installer

It may be possible to remove this wrapper now that [we add `vendor/bin/` to the `$PATH`](https://github.com/palantirnet/the-vagrant/blob/develop/conf/vagrant/provisioning/roles/common/tasks/main.yml#L34-L36) -- which is very convenient but still somewhat blunt, IMO, since what happens when you're running multiple projects on the same machine? We often do this when migrating from a D6 or D7 site to a D8 site.

**Comment by damontgomery** [comment]
Can drush launcher be installed and added to the path?

That should find drush in the vendor folder.

**Comment by becw** [comment]
I wonder if it would make more sense to copy the `drush.wrapper` script from the drush examples and use that to specify our `drushrc.php` -- since that's the unique thing this script is doing. As you point out, Drush itself will handle the other part of this (finding the project-specific drush).

In the meantime, this PR #53 also solves this issue.

**Comment by damontgomery** [comment]
I'm not sure if this helps, but I found the following about `drush.yml` as a replacement for `drushrc.php` in Drush 9. https://github.com/drush-ops/drush/issues/3027

**Comment by becw** [comment]
I've merged #53 as a fix for this issue. It will be included in the next release.
