### ISSUE TITLE
Composer not in PATH

### ISSUE THREAD

**Issue by patrickfweston** [palantirnet/the-vagrant#39]
While helping Malak install the skeleton, he received the following error:

```
The executable "composer" Vagrant is trying to trigger
was not found. If you know it is not in the PATH, please
specify its absolute path using the :append_to_path option.
```

It looks like it's related to: https://github.com/palantirnet/the-vagrant/blob/c116b4aa1536d212bd3356c050d9c03307f0ca81/conf/vagrant/Vagrantfile#L77

I had him remove that section and the box installed like normal. It was complaining that it couldn't run `composer install --ignore-reqs`. However, we could run this command manually just fine.

**Comment by becw** [comment]
I think I'd like to remove the `composer install` step from the `Vagrantfile` anyway:
* During active development, it doesn't help, since folks already have their vm up and running
* During support, it might help, but then also there aren't necessarily frequent composer dependency changes

What do you think?

**Comment by patrickfweston** [comment]
I think that seems reasonable. It is a little unnecessary / redundant and could speed things up a little bit. I think that would solve this issue though.

**Comment by becw** [comment]
I ran into this issue with @MalakDesai the other day. It turns out that this pops up when you've added a command alias for composer to your `.profile` or `.bash_profile` like this:

```
alias composer='/usr/local/bin/composer.phar'
```

If you've done this, you'll find that your shell doesn't actually have the executable in your `PATH`; you can see this when the `which` command doesn't return an absolute path for `composer`:

```
[12:35P white@laptop:~] $ which composer.phar
/usr/local/bin/composer.phar
[12:35P white@laptop:~] $ which composer
[12:35P white@laptop:~] $ 
```

A more robust way to set up the `composer` command is to remove that alias line from your bash configuration and instead symlink `composer.phar` to `composer`:

```
ln -s /usr/local/bin/composer.phar /usr/local/bin/composer
```

**Comment by becw** [comment]
Also, following the composer install instructions in https://github.com/palantirnet/documentation/wiki/Mac-Setup should resolve this issue in general. Those instructions are:

> Follow the [instructions on getcomposer.org](https://getcomposer.org/download/), but run the setup script with: `php composer-setup.php --install-dir=/usr/local/bin --filename=composer`<br>Update regularly with `composer self-update`
