### ISSUE TITLE
Configure the git user based on the host machine

### ISSUE THREAD

**Issue by becw** [palantirnet/the-vagrant#57]
It would be great if we could set the git `user.name` and `user.email` based on the user's host, so that commits made within the Vagrant environment were properly attributed (per [the-build #66](https://github.com/palantirnet/the-build/issues/66)).

**Comment by byrond** [comment]
Copying the `.gitconfig` seems to be a common example:
https://www.vagrantup.com/docs/provisioning/file.html

We could either add that into the `Vagrantfile` or include it with the other Ansible provisioning.

My `.gitconfig` has a global gitignore specified, so that path would need to be translated and that file copied in, too (if that's a frequent inclusion).

**Comment by byrond** [comment]
We also may want to prompt the user to configure Git, if they don't have a `.gitconfig`.

**Comment by becw** [comment]
Released in [version 2.2.2](https://github.com/palantirnet/the-vagrant/releases/tag/2.2.2). Thanks, @byrond!
